### ISSUE TITLE
Doesn't work with wheel >= 0.32

### ISSUE THREAD

**Issue by mig4** [facebookincubator/xar#24]
xar crashes with the latest version of wheel >= 0.32.0:

```
Traceback (most recent call last):
  File "/home/mig4/.local/share/virtualenvs/xarred-e18hcFi1/bin/make_xar", line 7, in <module>
    from xar.make_xar import main
  File "/home/mig4/.local/share/virtualenvs/xarred-e18hcFi1/lib/python3.7/site-packages/xar/make_xar.py", line 37, in <module>
    from xar import py_util, xar_builder, xar_util
  File "/home/mig4/.local/share/virtualenvs/xarred-e18hcFi1/lib/python3.7/site-packages/xar/py_util.py", line 24, in <module>
    from wheel import install, paths, pep425tags, pkginfo
ImportError: cannot import name 'install' from 'wheel' (/home/mig4/.local/share/virtualenvs/xarred-e18hcFi1/lib/python3.7/site-packages/wheel/__init__.py)
```

It looks like this is because the `wheel.install` module was split and part moved to `wheel.cli.install` and the `WheelFile` class was moved into its own module `wheel.wheelfile` in pypa/wheel@89492505b968f6bf9ae9cc35f88f8ecd6ce6cbf1

**Comment by cooperlees** [comment]
Hi,

Thanks for reporting. We are aware and I will look next week to get a fix out next week. At the moment we hard set wheel to <= 0.31.1 for this very reason: 
https://github.com/facebookincubator/xar/blob/master/setup.py#L36

PRs are also welcome if you need this sooner.

**Comment by cooperlees** [comment]
We've vendored wheel to a version with the libraries we need - Release coming soon.
